[project]
name = "lightcast"
version = "1.0.0"
description = "A lightweight Python library for searching and downloading podcasts with zero dependencies."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
lightcast = "lightcast.__main__:main"
