name: Run Tests
  
on: [push]  
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5.2.1
      - name: Install Python
        run: uv python install
      - name: Install dev dependencies
        run: uv sync --dev
      - name: Run tests
        run: uvx pytest tests
